services:
  - type: web
    name: ai-image-detector
    runtime: docker
    plan: free # or your preferred plan
    region: oregon # or your preferred region
    envVars:
      - key: PORT
        value: 8301
